---
title: "Manuscript Unformatted"
author: "Craig McGowan"
date: "November 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(FluSight)
library(cdcfluview)

knitr::opts_chunk$set(echo = FALSE)
```

# Abstract

# Intro

* Flu is bad - here's why

* Why forecast flu

* Summary of other methodologies

* CDC challenge

* What this paper does

# Methods

* Development of harmonic model only - ignore subtype hist avg and ensemble

* CV steps

* Development of 'prospective' forecasts

* Scoring rules

# Results

* Summary results from each test season

* Comparisons across seasons and locations and targets

* Check Nick's papers for potential comparisons and graphs that could be made

* Comparisons to CDC results using relevant scoring rules

# Discussion

* New modeling approach compared to previous literature

* Strong performance compared to existing models

* Submitted as true prospective model during 18/19 season and can evaluate further then (slash maybe wait until season is over)

* Strengths - fairly simple mathematical model, easy to implement with existing software

* Limitations - current analysis assumes Google Trend data are 